package br.com.fabiano.jediormtest.models;

import jedi.db.models.CharField;
import jedi.db.models.Manager;
import jedi.db.models.Model;
import jedi.db.models.QuerySet;
import jedi.db.models.Table;

@Table(name = "clientes", engine = "InnoDB", charset = "utf8", comment = "Table of clientes")
public class Cliente extends Model {
	private static final long serialVersionUID = -5346862175579125596L;
	
	@CharField(max_length=50)
	private String nome;

	public static Manager objects = new Manager(Cliente.class);
	
	public Cliente() {
		super();
	}

	public Cliente(String nome) {
		super();
		this.nome = nome;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Override
	public String toString() {
		return "Cliente [nome=" + nome + "]";
	}


    // Generated by Jedi ORM
    public QuerySet<Telefone> getTelefoneSet() {
        return Telefone.objects.getSet(Cliente.class, this.id);
    }
}
